@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([specified client does not exist])
    -Error: Client not found.
    stop
else ([else])
    if () then ([specified client's meeting does not exist])
        -Error: Meeting not found.
        stop
    else ([else])
        :Specified meeting is deleted;
        stop
endif
@enduml
