@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes EditMeeting command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if (Valid parameters and
new meeting is not
        duplicate) then ([Execute command])
    :Delete old meeting in addressbook and client's meeting list;
    :Add new meeting in addressbook and client's meeting list;
else ([Throw exception])
endif
stop
@enduml
